version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: employee
      MYSQL_PASSWORD: employee123

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  employee-app:

    build: .

    container_name: employee-app

    depends_on:
      - mysql

    ports:
      - "8081:8081"

    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: employee123

volumes:

  mysql-data:
